name: Lab 4 Helm Validation

on:
  push:
    branches:
      - master
      - lab4

jobs:
  helm-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.0'

      - name: Run Lab4 validation script
        run: |
          chmod +x ./tests/lab4_test.sh
          ./tests/lab4_test.sh