name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - lab4

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GHCR_OWNER: nazaryimontytskyi

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GHCR_OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.GHCR_OWNER }}/ecommerce-app:latest
            ghcr.io/${{ env.GHCR_OWNER }}/ecommerce-app:sha-${{ github.sha }}

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ env.GHCR_OWNER }}/ecommerce-app:latest
          format: table
          exit-code: 0
          severity: CRITICAL
  lab3:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install KinD
        uses: helm/kind-action@v1.9.0

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/

      - name: Wait for Deployment rollout
        run: |
          kubectl rollout status deployment/ecommerce-app --timeout=60s

      - name: Diagnostic Check
        if: always()
        run: |
          echo ">>> Pods state:"
          kubectl get pods
          echo ">>> Description of a problematic pod:"
          kubectl describe pod -l app=ecommerce
          echo ">>> Final apps logs:"
          kubectl logs -l app=ecommerce --tail=100

      - name: Run Lab3 validation script
        run: |
          chmod +x ./tests/lab3_test.sh
          ./tests/lab3_test.sh