name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - lab2

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GHCR_OWNER: nazaryimontytskyi

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GHCR_OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.GHCR_OWNER }}/ecommerce-app:latest
            ghcr.io/${{ env.GHCR_OWNER }}/ecommerce-app:sha-${{ github.sha }}

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ env.GHCR_OWNER }}/ecommerce-app:latest
          format: table
          exit-code: 0
          severity: CRITICAL

      - name: Run Grading Script
        run: |
          chmod +x ./tests/lab1_test.sh
          ./tests/lab1_test.sh

      - name: Run Master Validation Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./tests/lab2_test.sh
          ./tests/lab2_test.sh